import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          HomePage(),
        ]),
      ),
    );
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 375,
          height: 667,
          padding: const EdgeInsets.only(top: 32, bottom: 13.47),
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Color(0xFFF6FCFC),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(20),
            ),
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            mainAxisAlignment: MainAxisAlignment.end,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Container(
                width: 375,
                height: 621.53,
                child: Stack(
                  children: [
                    Positioned(
                      left: 0,
                      top: 581,
                      child: Container(
                        width: 375,
                        height: 40.53,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 375,
                                decoration: ShapeDecoration(
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(
                                      width: 1.50,
                                      strokeAlign: BorderSide.strokeAlignCenter,
                                      color: Color(0xFF2A9D8F),
                                    ),
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: 46,
                              top: 14,
                              child: Container(
                                width: 289,
                                height: 26.53,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 91,
                                      top: 0,
                                      child: Container(width: 25, height: 25, child: Stack()),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    Positioned(
                      left: 22,
                      top: 61,
                      child: Container(
                        width: 347,
                        height: 218,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 347,
                                height: 218,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 0,
                                      top: 17,
                                      child: Container(
                                        width: 333,
                                        height: 174,
                                        decoration: ShapeDecoration(
                                          color: Color(0xFF2A9D8F),
                                          shape: RoundedRectangleBorder(
                                            borderRadius: BorderRadius.circular(15),
                                          ),
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 20,
                                      top: 0,
                                      child: Container(
                                        width: 327,
                                        height: 218,
                                        child: Stack(
                                          children: [
                                            Positioned(
                                              left: 0,
                                              top: 32,
                                              child: Container(
                                                width: 188,
                                                height: 107,
                                                child: Stack(
                                                  children: [
                                                    Positioned(
                                                      left: 0,
                                                      top: 0,
                                                      child: Text(
                                                        'Покупайте лекарство\nбыстро и легко,',
                                                        style: TextStyle(
                                                          color: Color(0xFFD1EFEB),
                                                          fontSize: 18,
                                                          fontFamily: 'Istok Web',
                                                          fontWeight: FontWeight.w700,
                                                          height: 0,
                                                        ),
                                                      ),
                                                    ),
                                                    Positioned(
                                                      left: 0,
                                                      top: 72,
                                                      child: Container(
                                                        width: 102,
                                                        height: 35,
                                                        child: Stack(
                                                          children: [
                                                            Positioned(
                                                              left: 0,
                                                              top: 0,
                                                              child: Container(
                                                                width: 102,
                                                                height: 35,
                                                                decoration: ShapeDecoration(
                                                                  color: Color(0xFFD1EEEB),
                                                                  shape: RoundedRectangleBorder(
                                                                    borderRadius: BorderRadius.circular(20),
                                                                  ),
                                                                ),
                                                              ),
                                                            ),
                                                            Positioned(
                                                              left: 22,
                                                              top: 6,
                                                              child: Text(
                                                                'Каталог',
                                                                style: TextStyle(
                                                                  color: Color(0xFF2A9D8F),
                                                                  fontSize: 17,
                                                                  fontFamily: 'Istok Web',
                                                                  fontWeight: FontWeight.w400,
                                                                  height: 0,
                                                                ),
                                                              ),
                                                            ),
                                                          ],
                                                        ),
                                                      ),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                            ),
                                            Positioned(
                                              left: 109,
                                              top: 0,
                                              child: Container(
                                                width: 218,
                                                height: 218,
                                                decoration: BoxDecoration(
                                                  image: DecorationImage(
                                                    image: NetworkImage("https://via.placeholder.com/218x218"),
                                                    fit: BoxFit.fill,
                                                  ),
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 29,
                              top: 171,
                              child: Container(
                                width: 276,
                                height: 35,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 0,
                                      top: 0,
                                      child: Container(
                                        width: 276,
                                        height: 35,
                                        decoration: ShapeDecoration(
                                          color: Color(0xFFD1EEEB),
                                          shape: RoundedRectangleBorder(
                                            borderRadius: BorderRadius.circular(20),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    Positioned(
                      left: 24,
                      top: 0,
                      child: Container(
                        width: 330,
                        height: 62,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 226,
                                height: 62,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 0,
                                      top: 0,
                                      child: Text(
                                        'Приветствуем,',
                                        style: TextStyle(
                                          color: Color(0xFF2A9D8F),
                                          fontSize: 22,
                                          fontFamily: 'Istok Web',
                                          fontWeight: FontWeight.w400,
                                          height: 0,
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 0,
                                      top: 28,
                                      child: Text(
                                        'Айтбай Азина',
                                        style: TextStyle(
                                          color: Color(0xFF2A9D8F),
                                          fontSize: 30,
                                          fontFamily: 'Kulim Park',
                                          fontWeight: FontWeight.w600,
                                          height: 0,
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 270,
                              top: 6,
                              child: Container(
                                width: 60,
                                height: 56,
                                decoration: ShapeDecoration(
                                  image: DecorationImage(
                                    image: NetworkImage("https://via.placeholder.com/60x56"),
                                    fit: BoxFit.fill,
                                  ),
                                  shape: OvalBorder(),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    Positioned(
                      left: 29,
                      top: 270,
                      child: Container(
                        width: 315,
                        height: 297,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 9,
                              child: Container(
                                width: 146,
                                height: 135,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 0,
                                      top: 0,
                                      child: Container(
                                        width: 146,
                                        height: 135,
                                        decoration: ShapeDecoration(
                                          color: Color(0xFFD1EEEB),
                                          shape: RoundedRectangleBorder(
                                            borderRadius: BorderRadius.circular(10),
                                          ),
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 16,
                                      top: 8,
                                      child: Container(
                                        width: 119,
                                        height: 117,
                                        child: Stack(
                                          children: [
                                            Positioned(
                                              left: 0,
                                              top: 0,
                                              child: Container(
                                                width: 100,
                                                height: 87.45,
                                                decoration: BoxDecoration(
                                                  image: DecorationImage(
                                                    image: NetworkImage("https://via.placeholder.com/100x87"),
                                                    fit: BoxFit.fill,
                                                  ),
                                                ),
                                              ),
                                            ),
                                            Positioned(
                                              left: 1,
                                              top: 84,
                                              child: Container(
                                                width: 118,
                                                height: 33,
                                                child: Stack(
                                                  children: [
                                                    Positioned(
                                                      left: 0,
                                                      top: 0,
                                                      child: Container(
                                                        width: 75,
                                                        height: 33,
                                                        child: Stack(
                                                          children: [
                                                            Positioned(
                                                              left: 0,
                                                              top: 0,
                                                              child: Text(
                                                                'Тразадон',
                                                                style: TextStyle(
                                                                  color: Color(0xFF2A9D8F),
                                                                  fontSize: 15,
                                                                  fontFamily: 'Istok Web',
                                                                  fontWeight: FontWeight.w700,
                                                                  height: 0,
                                                                ),
                                                              ),
                                                            ),
                                                            Positioned(
                                                              left: 0,
                                                              top: 19,
                                                              child: Text(
                                                                'Успокоительное',
                                                                style: TextStyle(
                                                                  color: Color(0xFF2A9D8F),
                                                                  fontSize: 10,
                                                                  fontFamily: 'Istok Web',
                                                                  fontWeight: FontWeight.w400,
                                                                  height: 0,
                                                                ),
                                                              ),
                                                            ),
                                                          ],
                                                        ),
                                                      ),
                                                    ),
                                                    Positioned(
                                                      left: 78,
                                                      top: 7,
                                                      child: Text(
                                                        '500₸',
                                                        style: TextStyle(
                                                          color: Color(0xFF134F47),
                                                          fontSize: 17,
                                                          fontFamily: 'Istok Web',
                                                          fontWeight: FontWeight.w700,
                                                          height: 0,
                                                        ),
                                                      ),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 0,
                              top: 139,
                              child: Container(
                                width: 150,
                                height: 158,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 0,
                                      top: 23,
                                      child: Container(
                                        width: 146,
                                        height: 135,
                                        decoration: ShapeDecoration(
                                          color: Color(0xFFD1EEEB),
                                          shape: RoundedRectangleBorder(
                                            borderRadius: BorderRadius.circular(10),
                                          ),
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 0,
                                      top: 0,
                                      child: Container(
                                        width: 150,
                                        height: 150,
                                        child: Stack(
                                          children: [
                                            Positioned(
                                              left: 0,
                                              top: 0,
                                              child: Container(
                                                width: 150,
                                                height: 150,
                                                decoration: BoxDecoration(
                                                  image: DecorationImage(
                                                    image: NetworkImage("https://via.placeholder.com/150x150"),
                                                    fit: BoxFit.fill,
                                                  ),
                                                ),
                                              ),
                                            ),
                                            Positioned(
                                              left: 16,
                                              top: 115,
                                              child: Container(
                                                width: 119,
                                                height: 32,
                                                child: Stack(
                                                  children: [
                                                    Positioned(
                                                      left: 0,
                                                      top: 0,
                                                      child: Container(
                                                        width: 72,
                                                        height: 31,
                                                        child: Stack(
                                                          children: [
                                                            Positioned(
                                                              left: 1,
                                                              top: 17,
                                                              child: Text(
                                                                'Пробиотик',
                                                                style: TextStyle(
                                                                  color: Color(0xFF2A9D8F),
                                                                  fontSize: 10,
                                                                  fontFamily: 'Istok Web',
                                                                  fontWeight: FontWeight.w400,
                                                                  height: 0,
                                                                ),
                                                              ),
                                                            ),
                                                            Positioned(
                                                              left: 0,
                                                              top: 0,
                                                              child: Text(
                                                                'Ациполин',
                                                                style: TextStyle(
                                                                  color: Color(0xFF2A9D8F),
                                                                  fontSize: 15,
                                                                  fontFamily: 'Istok Web',
                                                                  fontWeight: FontWeight.w700,
                                                                  height: 0,
                                                                ),
                                                              ),
                                                            ),
                                                          ],
                                                        ),
                                                      ),
                                                    ),
                                                    Positioned(
                                                      left: 79,
                                                      top: 8,
                                                      child: Text(
                                                        '500₸',
                                                        style: TextStyle(
                                                          color: Color(0xFF134F47),
                                                          fontSize: 17,
                                                          fontFamily: 'Istok Web',
                                                          fontWeight: FontWeight.w700,
                                                          height: 0,
                                                        ),
                                                      ),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 169,
                              top: 0,
                              child: Container(
                                width: 146,
                                height: 144,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 0,
                                      top: 9,
                                      child: Container(
                                        width: 146,
                                        height: 135,
                                        decoration: ShapeDecoration(
                                          color: Color(0xFFD1EEEB),
                                          shape: RoundedRectangleBorder(
                                            borderRadius: BorderRadius.circular(10),
                                          ),
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 15,
                                      top: 0,
                                      child: Container(
                                        width: 122,
                                        height: 134,
                                        child: Stack(
                                          children: [
                                            Positioned(
                                              left: 0,
                                              top: 0,
                                              child: Container(
                                                width: 115,
                                                height: 99.50,
                                                decoration: BoxDecoration(
                                                  image: DecorationImage(
                                                    image: NetworkImage("https://via.placeholder.com/115x100"),
                                                    fit: BoxFit.fill,
                                                  ),
                                                ),
                                              ),
                                            ),
                                            Positioned(
                                              left: 1,
                                              top: 101,
                                              child: Container(
                                                width: 121,
                                                height: 33,
                                                child: Stack(
                                                  children: [
                                                    Positioned(
                                                      left: 0,
                                                      top: 0,
                                                      child: Container(
                                                        width: 72,
                                                        height: 33,
                                                        child: Stack(
                                                          children: [
                                                            Positioned(
                                                              left: 0,
                                                              top: 19,
                                                              child: Text(
                                                                'Слабительное',
                                                                style: TextStyle(
                                                                  color: Color(0xFF2A9D8F),
                                                                  fontSize: 10,
                                                                  fontFamily: 'Istok Web',
                                                                  fontWeight: FontWeight.w400,
                                                                  height: 0,
                                                                ),
                                                              ),
                                                            ),
                                                            Positioned(
                                                              left: 0,
                                                              top: 0,
                                                              child: Text(
                                                                'Памелтон',
                                                                style: TextStyle(
                                                                  color: Color(0xFF2A9D8F),
                                                                  fontSize: 15,
                                                                  fontFamily: 'Istok Web',
                                                                  fontWeight: FontWeight.w700,
                                                                  height: 0,
                                                                ),
                                                              ),
                                                            ),
                                                          ],
                                                        ),
                                                      ),
                                                    ),
                                                    Positioned(
                                                      left: 81,
                                                      top: 7,
                                                      child: Text(
                                                        '500₸',
                                                        style: TextStyle(
                                                          color: Color(0xFF134F47),
                                                          fontSize: 17,
                                                          fontFamily: 'Istok Web',
                                                          fontWeight: FontWeight.w700,
                                                          height: 0,
                                                        ),
                                                      ),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 169,
                              top: 162,
                              child: Container(
                                width: 146,
                                height: 135,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 0,
                                      top: 0,
                                      child: Container(
                                        width: 146,
                                        height: 135,
                                        decoration: ShapeDecoration(
                                          color: Color(0xFFD1EEEB),
                                          shape: RoundedRectangleBorder(
                                            borderRadius: BorderRadius.circular(10),
                                          ),
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 8,
                                      top: 4,
                                      child: Container(
                                        width: 129,
                                        height: 119,
                                        child: Stack(
                                          children: [
                                            Positioned(
                                              left: 0,
                                              top: 0,
                                              child: Container(
                                                width: 110,
                                                height: 88.09,
                                                decoration: BoxDecoration(
                                                  image: DecorationImage(
                                                    image: NetworkImage("https://via.placeholder.com/110x88"),
                                                    fit: BoxFit.fill,
                                                  ),
                                                ),
                                              ),
                                            ),
                                            Positioned(
                                              left: 8,
                                              top: 88,
                                              child: Container(
                                                width: 121,
                                                height: 31,
                                                child: Stack(
                                                  children: [
                                                    Positioned(
                                                      left: 0,
                                                      top: 0,
                                                      child: Container(
                                                        width: 71,
                                                        height: 31,
                                                        child: Stack(
                                                          children: [
                                                            Positioned(
                                                              left: 0,
                                                              top: 17,
                                                              child: Text(
                                                                'Антибиотик',
                                                                style: TextStyle(
                                                                  color: Color(0xFF2A9D8F),
                                                                  fontSize: 10,
                                                                  fontFamily: 'Istok Web',
                                                                  fontWeight: FontWeight.w400,
                                                                  height: 0,
                                                                ),
                                                              ),
                                                            ),
                                                            Positioned(
                                                              left: 0,
                                                              top: 0,
                                                              child: Text(
                                                                'Залеплон',
                                                                style: TextStyle(
                                                                  color: Color(0xFF2A9D8F),
                                                                  fontSize: 15,
                                                                  fontFamily: 'Istok Web',
                                                                  fontWeight: FontWeight.w700,
                                                                  height: 0,
                                                                ),
                                                              ),
                                                            ),
                                                          ],
                                                        ),
                                                      ),
                                                    ),
                                                    Positioned(
                                                      left: 81,
                                                      top: 5,
                                                      child: Text(
                                                        '500₸',
                                                        style: TextStyle(
                                                          color: Color(0xFF134F47),
                                                          fontSize: 17,
                                                          fontFamily: 'Istok Web',
                                                          fontWeight: FontWeight.w700,
                                                          height: 0,
                                                        ),
                                                      ),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
