import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          InfoPage(),
        ]),
      ),
    );
  }
}

class InfoPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 375,
          height: 667,
          padding: const EdgeInsets.only(top: 18, bottom: 12.47),
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Color(0xFFF6FCFC),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(20),
            ),
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            mainAxisAlignment: MainAxisAlignment.end,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Container(
                width: 375,
                height: 636.53,
                child: Stack(
                  children: [
                    Positioned(
                      left: 29.99,
                      top: 310,
                      child: Container(
                        width: 312.01,
                        height: 112,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0.01,
                              top: 0,
                              child: Container(
                                width: 312,
                                height: 112,
                                decoration: ShapeDecoration(
                                  color: Color(0xFFD1EEEB),
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(width: 1, color: Color(0xFF2A9D8F)),
                                    borderRadius: BorderRadius.circular(10),
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: 0,
                              top: 13,
                              child: Container(
                                width: 311.01,
                                height: 83,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 19.01,
                                      top: 0,
                                      child: Text(
                                        'Аптека  “Амир и Д”',
                                        style: TextStyle(
                                          color: Color(0xFF2A9D8F),
                                          fontSize: 18,
                                          fontFamily: 'Istok Web',
                                          fontWeight: FontWeight.w400,
                                          height: 0,
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 18.01,
                                      top: 21,
                                      child: Container(
                                        width: 47,
                                        height: 16,
                                        child: Stack(
                                          children: [
                                            Positioned(
                                              left: 0,
                                              top: 0,
                                              child: Container(
                                                width: 16,
                                                height: 16,
                                                clipBehavior: Clip.antiAlias,
                                                decoration: BoxDecoration(),
                                                child: FlutterLogo(),
                                              ),
                                            ),
                                            Positioned(
                                              left: 16,
                                              top: 0,
                                              child: Container(
                                                width: 16,
                                                height: 16,
                                                clipBehavior: Clip.antiAlias,
                                                decoration: BoxDecoration(),
                                                child: FlutterLogo(),
                                              ),
                                            ),
                                            Positioned(
                                              left: 31,
                                              top: 0,
                                              child: Container(
                                                width: 16,
                                                height: 16,
                                                clipBehavior: Clip.antiAlias,
                                                decoration: BoxDecoration(),
                                                child: FlutterLogo(),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 19.01,
                                      top: 59,
                                      child: Container(
                                        width: 274,
                                        height: 24,
                                        child: Stack(
                                          children: [
                                            Positioned(
                                              left: 0,
                                              top: 0,
                                              child: Container(
                                                width: 130,
                                                height: 24,
                                                child: Stack(
                                                  children: [
                                                    Positioned(
                                                      left: 0,
                                                      top: 0,
                                                      child: Container(
                                                        width: 130,
                                                        height: 24,
                                                        decoration: ShapeDecoration(
                                                          shape: RoundedRectangleBorder(
                                                            side: BorderSide(width: 1, color: Color(0xFF2A9D8F)),
                                                            borderRadius: BorderRadius.circular(5),
                                                          ),
                                                        ),
                                                      ),
                                                    ),
                                                    Positioned(
                                                      left: 41,
                                                      top: 1,
                                                      child: Text(
                                                        'Купить',
                                                        style: TextStyle(
                                                          color: Color(0xFF2A9D8F),
                                                          fontSize: 15,
                                                          fontFamily: 'Istok Web',
                                                          fontWeight: FontWeight.w400,
                                                          height: 0,
                                                        ),
                                                      ),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                            ),
                                            Positioned(
                                              left: 144,
                                              top: 0,
                                              child: Container(
                                                width: 130,
                                                height: 24,
                                                child: Stack(
                                                  children: [
                                                    Positioned(
                                                      left: 0,
                                                      top: 0,
                                                      child: Container(
                                                        width: 130,
                                                        height: 24,
                                                        decoration: ShapeDecoration(
                                                          shape: RoundedRectangleBorder(
                                                            side: BorderSide(width: 1, color: Color(0xFF2A9D8F)),
                                                            borderRadius: BorderRadius.circular(5),
                                                          ),
                                                        ),
                                                      ),
                                                    ),
                                                    Positioned(
                                                      left: 31,
                                                      top: 2,
                                                      child: Text(
                                                        'В корзину',
                                                        style: TextStyle(
                                                          color: Color(0xFF2A9D8F),
                                                          fontSize: 15,
                                                          fontFamily: 'Istok Web',
                                                          fontWeight: FontWeight.w400,
                                                          height: 0,
                                                        ),
                                                      ),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    Positioned(
                      left: 30,
                      top: 459,
                      child: Container(
                        width: 312,
                        height: 112,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 312,
                                height: 112,
                                decoration: ShapeDecoration(
                                  color: Color(0xFFD1EEEB),
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(width: 1, color: Color(0xFF2A9D8F)),
                                    borderRadius: BorderRadius.circular(10),
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: 0,
                              top: 8,
                              child: Container(
                                width: 311.01,
                                height: 84,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 15,
                                      top: 0,
                                      child: Text(
                                        'Аптека  “Садыхан”',
                                        style: TextStyle(
                                          color: Color(0xFF2A9D8F),
                                          fontSize: 18,
                                          fontFamily: 'Istok Web',
                                          fontWeight: FontWeight.w400,
                                          height: 0,
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 15,
                                      top: 20,
                                      child: Container(
                                        width: 47,
                                        height: 16,
                                        child: Stack(
                                          children: [
                                            Positioned(
                                              left: 0,
                                              top: 0,
                                              child: Container(
                                                width: 16,
                                                height: 16,
                                                clipBehavior: Clip.antiAlias,
                                                decoration: BoxDecoration(),
                                                child: FlutterLogo(),
                                              ),
                                            ),
                                            Positioned(
                                              left: 16,
                                              top: 0,
                                              child: Container(
                                                width: 16,
                                                height: 16,
                                                clipBehavior: Clip.antiAlias,
                                                decoration: BoxDecoration(),
                                                child: FlutterLogo(),
                                              ),
                                            ),
                                            Positioned(
                                              left: 31,
                                              top: 0,
                                              child: Container(
                                                width: 16,
                                                height: 16,
                                                clipBehavior: Clip.antiAlias,
                                                decoration: BoxDecoration(),
                                                child: FlutterLogo(),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 19,
                                      top: 60,
                                      child: Container(
                                        width: 274,
                                        height: 24,
                                        child: Stack(
                                          children: [
                                            Positioned(
                                              left: 144,
                                              top: 0,
                                              child: Container(
                                                width: 130,
                                                height: 24,
                                                child: Stack(
                                                  children: [
                                                    Positioned(
                                                      left: 0,
                                                      top: 0,
                                                      child: Container(
                                                        width: 130,
                                                        height: 24,
                                                        decoration: ShapeDecoration(
                                                          shape: RoundedRectangleBorder(
                                                            side: BorderSide(width: 1, color: Color(0xFF2A9D8F)),
                                                            borderRadius: BorderRadius.circular(5),
                                                          ),
                                                        ),
                                                      ),
                                                    ),
                                                    Positioned(
                                                      left: 31,
                                                      top: 1,
                                                      child: Text(
                                                        'В корзину',
                                                        style: TextStyle(
                                                          color: Color(0xFF2A9D8F),
                                                          fontSize: 15,
                                                          fontFamily: 'Istok Web',
                                                          fontWeight: FontWeight.w400,
                                                          height: 0,
                                                        ),
                                                      ),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                            ),
                                            Positioned(
                                              left: 0,
                                              top: 0,
                                              child: Container(
                                                width: 130,
                                                height: 24,
                                                child: Stack(
                                                  children: [
                                                    Positioned(
                                                      left: 0,
                                                      top: 0,
                                                      child: Container(
                                                        width: 130,
                                                        height: 24,
                                                        decoration: ShapeDecoration(
                                                          shape: RoundedRectangleBorder(
                                                            side: BorderSide(width: 1, color: Color(0xFF2A9D8F)),
                                                            borderRadius: BorderRadius.circular(5),
                                                          ),
                                                        ),
                                                      ),
                                                    ),
                                                    Positioned(
                                                      left: 41,
                                                      top: 1,
                                                      child: Text(
                                                        'Купить',
                                                        style: TextStyle(
                                                          color: Color(0xFF2A9D8F),
                                                          fontSize: 15,
                                                          fontFamily: 'Istok Web',
                                                          fontWeight: FontWeight.w400,
                                                          height: 0,
                                                        ),
                                                      ),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    Positioned(
                      left: 0,
                      top: 595,
                      child: Container(
                        width: 375,
                        height: 41.53,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 375,
                                decoration: ShapeDecoration(
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(
                                      width: 1.50,
                                      strokeAlign: BorderSide.strokeAlignCenter,
                                      color: Color(0xFF2A9D8F),
                                    ),
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: 46,
                              top: 15,
                              child: Container(
                                width: 289,
                                height: 26.53,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 92,
                                      top: 0,
                                      child: Container(width: 25, height: 25, child: Stack()),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    Positioned(
                      left: 18,
                      top: 0,
                      child: Container(
                        width: 324,
                        height: 289,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 31,
                              top: 257,
                              child: Text(
                                'Амбробене',
                                style: TextStyle(
                                  color: Color(0xFF2A9D8F),
                                  fontSize: 22,
                                  fontFamily: 'Istok Web',
                                  fontWeight: FontWeight.w400,
                                  height: 0,
                                ),
                              ),
                            ),
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 324,
                                height: 233,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 11,
                                      top: 33,
                                      child: Container(
                                        width: 312,
                                        height: 200,
                                        decoration: ShapeDecoration(
                                          color: Colors.white,
                                          shape: RoundedRectangleBorder(
                                            borderRadius: BorderRadius.circular(10),
                                          ),
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 12,
                                      top: 33,
                                      child: Container(
                                        width: 312,
                                        height: 200,
                                        decoration: ShapeDecoration(
                                          image: DecorationImage(
                                            image: NetworkImage("https://via.placeholder.com/312x200"),
                                            fit: BoxFit.fill,
                                          ),
                                          shape: RoundedRectangleBorder(
                                            side: BorderSide(width: 1, color: Color(0xFF2A9D8F)),
                                            borderRadius: BorderRadius.circular(10),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}